# Generated by Django 4.2.7 on 2023-11-16 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
