# Generated by Django 4.2.7 on 2023-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctedsentence",
            name="create_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
