# Generated by Django 4.2.7 on 2023-11-07 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_correctedsentence_create_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctedsentence",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RenameField(
            model_name="correctedsentence",
            old_name="create_on",
            new_name="created_on",
        ),
    ]
